plugin:
    name: 'leaderinternet.documentation::lang.plugin.name'
    description: 'leaderinternet.documentation::lang.plugin.description'
    author: 'Leader Internet'
    icon: oc-icon-book
    homepage: ''
navigation:
    documentation:
        label: Manual
        url: leaderinternet/documentation/documentation
        icon: icon-book
        permissions:
            - leaderinternet.documentation.manage_docs
permissions:
    leaderinternet.documentation.manage_docs:
        tab: 'leaderinternet.documentation::lang.plugin.name'
        label: 'leaderinternet.documentation::lang.documentation_manage_manual'